### ISSUE TITLE
Please Add License

### ISSUE THREAD

**Issue by aarongreenlee** [neelance/astrewrite#1]
Hello! Your project has been included as a dependency to `github.com/gopherjs/gopherjs`. Unfortunately, there is no license defined for your project which is preventing me from using it. I was hoping you could please add a license similar to your Sourcemap repo?

https://github.com/neelance/sourcemap/blob/master/LICENSE

Thanks,

Aaron Greenlee

**Comment by neelance** [comment]
I forgot that. Thanks for reporting.
